apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ex3
resources:
- gitrepo.yaml
- imagerepo.yaml
- imagepolicy.yaml
- imageupdate.yaml
- flux-system-gitrepo.yaml
- github.com/kingdonb/podinfo//deploy/overlays/production?ref=master
patchesStrategicMerge:
- |-
  $patch: delete
  apiVersion: v1
  kind: Namespace
  metadata:
    name: production
images:
- name: ghcr.io/kingdonb/podinfo
  newName: ghcr.io/kingdonb/podinfo # {"$imagepolicy": "ex3:prod-policy:name"}
  newTag: 6.0.5 # {"$imagepolicy": "ex3:prod-policy:tag"}
